### ISSUE TITLE
Application crashes in Call button event

### ISSUE THREAD

**Issue by fowzaj** [Azure-Samples/communication-services-android-quickstarts#2]
I am facing below crash while using call feature in given sample. Any help would be appreciated.

   --------- beginning of crash
2021-01-08 22:32:12.667 10971-10971/com.contoso.acsquickstart E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.contoso.acsquickstart, PID: 10971
    java.lang.UnsatisfiedLinkError: No implementation found for com.azure.communication.calling.status com.azure.communication.calling.NativeLibrary.sam_start_call_options_create(com.azure.communication.calling.Out) (tried Java_com_azure_communication_calling_NativeLibrary_sam_1start_1call_1options_1create and Java_com_azure_communication_calling_NativeLibrary_sam_1start_1call_1options_1create__Lcom_azure_communication_calling_Out_2)
        at com.azure.communication.calling.NativeLibrary.sam_start_call_options_create(Native Method)
        at com.azure.communication.calling.StartCallOptions.<init>(StartCallOptions.java:45)
        at com.contoso.acsquickstart.MainActivity.startCall(MainActivity.java:67)
        at com.contoso.acsquickstart.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:43)
        at com.contoso.acsquickstart.-$$Lambda$MainActivity$3djR4rWnSHXW7DfAvror0YWBYps.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7213)
        at android.view.View.performClickInternal(View.java:7187)
        at android.view.View.access$3500(View.java:828)
        at android.view.View$PerformClick.run(View.java:27675)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by kagbakpem** [comment]
Hello @fowzaj, which version of the Azure Communication Services Calling SDK are you using? Version 1.0.0-beta.5 provides support for all Android ABIs. Please make sure you use that version for full compatibility against all devices. If the issue persists after switching to 1.0.0-beta.5, feel free to ping this thread again.

**Comment by fowzaj** [comment]
Hi @kagbakpem , 
Really appreciate your response. And i tried with latest version as you suggested like below

 implementation 'com.azure.android:azure-communication-calling:1.0.0-beta.5'

And the error is same as previous one. Thanks for your help

**Comment by kagbakpem** [comment]
@fowzaj, are you running this on device or simualtor? And if so, which ABI are you using?

**Comment by fowzaj** [comment]
Hi @kagbakpem ,
I tried both Device(Huwei P30,Samsung Tab etc) and emulator but end up with same result
![image](https://user-images.githubusercontent.com/17097204/104757413-7aa01100-5776-11eb-87f5-5fddf059aa2a.png)
