### ISSUE TITLE
Teams call example does not work

### ISSUE THREAD

**Issue by mihai1voicescu** [Azure-Samples/communication-services-android-quickstarts#21]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Checkout code
2. Replace UserToken
3. Run app
4. Insert a teams meeting url, taken from any working Teams deployment. Eg: `https://teams.live.com/meet/94328405378685`
5. App crashes on join

### Any log messages given by the failure
```
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.contoso.acsquickstart, PID: 26868
    java.lang.IllegalArgumentException: Invalid server call Id because it's empty or has invalid values.
        at com.azure.android.communication.calling.NativeLibraryHelpers.checkStatus(NativeLibraryHelpers.java:134)
        at com.azure.android.communication.calling.CallAgent.joinInternal(CallAgent.java:228)
        at com.azure.android.communication.calling.CallAgent.join(CallAgent.java:290)
        at com.contoso.acsquickstart.MainActivity.joinTeamsMeeting(MainActivity.java:72)
        at com.contoso.acsquickstart.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:45)
        at com.contoso.acsquickstart.-$$Lambda$MainActivity$3djR4rWnSHXW7DfAvror0YWBYps.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:8160)
        at android.widget.TextView.performClick(TextView.java:16104)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30250)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process: Sending signal. PID: 26868 SIG: 9
```

### Expected/desired behavior
Joining the call to work, as it does on web platform.

### OS and Version?
Android 11

### Versions
>

### Mention any other details that might be useful
Link is taken from a random teams account. Maybe that is the problem but the error message is very vague.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mihai1voicescu** [comment]
Is this project still active/relevant?

**Comment by erva** [comment]
Try just id 94328405378685 from link. In that case app doesn't crash, you see toast "Connected" but sample doesn't connect call. So still not working.
