### ISSUE TITLE
Android SDK crashing when instantiating CallAgentOptions

### ISSUE THREAD

**Issue by paolo-ermit** [Azure-Samples/communication-services-android-quickstarts#23]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
 Create a project, add to gradle
 >  implementation 'com.azure.android:azure-communication-calling:2.0.0'

Anywhere in the code add
> CallAgentOptions callOptions = new CallAgentOptions();

### Any log messages given by the failure
>   java.lang.UnsatisfiedLinkError: No implementation found for com.azure.android.communication.calling.status com.azure.android.communication.calling.NativeLibrary.sam_call_agent_options_create(com.azure.android.communication.calling.Out) (tried Java_com_azure_android_communication_calling_NativeLibrary_sam_1call_1agent_1options_1create and Java_com_azure_android_communication_calling_NativeLibrary_sam_1call_1agent_1options_1create__Lcom_azure_android_communication_calling_Out_2)
        at com.azure.android.communication.calling.NativeLibrary.sam_call_agent_options_create(Native Method)
        at com.azure.android.communication.calling.CallAgentOptions.<init>(CallAgentOptions.java:53)

### Expected/desired behavior
I would expect to be able to use the CallAgentOptions as parameter in 
> CallClient.createCallAgent(....)

### OS and Version?
Android 12

### Versions
com.azure.android:azure-communication-calling:2.0.0

### Mention any other details that might be useful
Without trying to use CallAgentOptions I can perform a call without any issue.
> ---------------------------------------------------------------

**Comment by paolo-ermit** [comment]
Created the issue in a more appropriate repository (https://github.com/Azure/azure-sdk-for-android/issues/984)
