### ISSUE TITLE
Cannot createAgent in sdk com.azure.android:azure-communication-calling:2.9.0

### ISSUE THREAD

**Issue by Mr-Mudasir** [Azure-Samples/communication-services-android-quickstarts#61]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Mudasir8224** [comment]
2024-09-02 15:45:33.432 20970-21017 System.err              com.contoso.acsquickstart            W  Caused by: java.lang.IllegalArgumentException: Unknown error.
2024-09-02 15:45:33.432 20970-21017 System.err              com.contoso.acsquickstart            W      at com.azure.android.communication.calling.NativeLibraryHelpers.checkStatus(NativeLibraryHelpers.java:250)
2024-09-02 15:45:33.432 20970-21017 System.err              com.contoso.acsquickstart            W      at com.azure.android.communication.calling.CallClient$1.get(CallClient.java:155)
2024-09-02 15:45:33.432 20970-21017 System.err              com.contoso.acsquickstart            W      at com.azure.android.communication.calling.CallClient$1.get(CallClient.java:148)

**Comment by Mr-Mudasir** [comment]
System.err              com.contoso.acsquickstart            java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unknown error.
 System.err              com.contoso.acsquickstart            at  java9.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:399)
 System.err              com.contoso.acsquickstart            at  java9.util.concurrent.CompletableFuture.get(CompletableFuture.java:2079)
 System.err              com.contoso.acsquickstart            at  com.azure.android.communication.calling.CallClient$5.get(CallClient.java:287)
 System.err              com.contoso.acsquickstart            at  com.azure.android.communication.calling.CallClient$5.get(CallClient.java:255)
 System.err              com.contoso.acsquickstart            at  java9.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1774)
